# Generated by Django 3.2.7 on 2021-09-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_basket_basketitems_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
