# Generated by Django 3.2.8 on 2021-10-11 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211005_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
