# Generated by Django 3.2.7 on 2021-12-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Dublin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(default='Dublin', max_length=50),
            preserve_default=False,
        ),
    ]
