# Generated by Django 3.2.7 on 2021-12-14 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_ordered',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
