# Generated by Django 3.2.7 on 2021-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211214_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
