# Generated by Django 3.2.7 on 2021-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
