# Generated by Django 3.2.7 on 2021-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20211215_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
